# .pre-commit-config.yaml

---	
repos:
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       stages: [commit]
  #       entry: pylint
  #       language: system
  #       types: [python]
        # args:
        # [
        #    "" 
        # ]
  
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks: 
      - id: flake8

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       name: isort (python)
