#config.yaml
name: i_em_de_be
method: grid 
metric: 
  name: Validation_accuracy
  goal: maximize
parameters: 
  learning_rate:
    values: [1e-4]
  batch_size:
    values: [16]
  optimizer_algorithm:
    values: ['adam']