#config.yaml
name: imdb_big_run_local_v5_ish
method: bayes 
metric: 
  name: Validation_accuracy
  goal: maximize
parameters: 
  learning_rate:
    values: [1e-4, 1e-3, 1e-2]
  batch_size:
    values: [16, 22, 64]
  optimizer_algorithm:
    values: ['adam', 'sgd']