#config.yaml
name: pablo_og_pedes_imdb_run
method: bayes 
metric: 
  name: Validation_accuracy
  goal: maximize
parameters: 
  learning_rate:
    values: [1e-4, 1e-3, 1e-2]
  batch_size:
    values: [16, 32, 64]
  optimizer_algorithm:
    values: ['adam', 'sgd']